name: GitHub Actions Demo
on: [push]
jobs:
  Get-Latest-Zfs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |-
          printf "::set-output name=matrix::"; curl -s 'https://api.github.com/repos/openzfs/zfs/releases' | jq -c '.[0] | [.tag_name]'
  Get-Latest-Fedora-Kernels:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |-
          printf "::set-output name=matrix::"; curl -s 'https://bodhi.fedoraproject.org/updates/?search=kernel&status=testing&status=stable&releases=__current__' | jq -c '.updates | [.[] | {kernel: .builds[] | select(.nvr | test("^kernel-\\d")) | .nvr, release: .release.version}]'
  Build-Rpms:
    needs:
      - Get-Latest-Zfs
      - Get-Latest-Fedora-Kernels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zfs: ${{fromJson(needs.Get-Latest-Zfs.outputs.matrix)}}
        fedora: ${{fromJson(needs.Get-Latest-Fedora-Kernels.outputs.matrix)}}
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: get zfs source
        run: |-
          wget https://github.com/openzfs/zfs/releases/download/${{matrix.zfs}}/${{matrix.zfs}}.tar.gz
      - name: cache packages
        id: cache-packages
        uses: actions/cache@v3
        env:
          cache-name: cache-packages
        with:
          path: ./packages/*.rpm
          key: ${{matrix.fedora.release}}-${{matrix.fedora.kernel}}-${{matrix.zfs}}
      - name: do build
        if: ${{ steps.cache-packages.outputs.cache-hit != 'true' }}
        run: |-
          docker run --interactive --rm -v $PWD:/data:z fedora:${{matrix.fedora.release}} /data/build.sh ${{matrix.fedora.release}} ${{matrix.fedora.kernel}} ${{matrix.zfs}}
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.fedora.release}}-${{matrix.fedora.kernel}}-${{matrix.zfs}}.rpm
          path: ./packages/*.rpm
  Build-Repo:
    needs:
      - Build-Rpms
    runs-on: ubuntu-latest
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v3
      - name: do something
        run: |-
          find . -iname \*.rpm

