name: GitHub Actions Demo
on: [push]
jobs:
  Get-Latest-Zfs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |-
          printf "::set-output name=matrix::"; curl -s 'https://api.github.com/repos/openzfs/zfs/releases' | jq -c '.[0] | [.tag_name]'
  Get-Latest-Fedora-Kernels:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |-
          printf "::set-output name=matrix::"; curl -s 'https://bodhi.fedoraproject.org/updates/?search=kernel&status=testing&status=stable&releases=__current__' | jq -c '.updates | [.[] | {kernel: .builds[] | select(.nvr | test("^kernel-\\d")) | .nvr, release: .release.version}]'
  Build-Rpms:
    needs:
      - Get-Latest-Zfs
      - Get-Latest-Fedora-Kernels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zfs: ${{fromJson(needs.Get-Latest-Zfs.outputs.matrix)}}
        fedora: ${{fromJson(needs.Get-Latest-Fedora-Kernels.outputs.matrix)}}
    steps:
      - run: |-
          echo matrix version: ${{ matrix.zfs }}
          echo fedora version: ${{ matrix.fedora.release }}